ALTER TABLE pessoas 
ADD COLUMN profissao VARCHAR(10);

ALTER TABLE pessoas
DROP COLUMN profissao;

#EXISTEM AFTER E FIRST
ALTER TABLE pessoas 
ADD COLUMN profissao VARCHAR(10) AFTER nome;

ALTER TABLE pessoas 
MODIFY COLUMN profissao VARCHAR(20);

ALTER TABLE pessoas
RENAME TO usuarios;

#CRIA NOVA TABELA PARA DEPOIS ALTERAR
CREATE TABLE IF NOT EXISTS cursos(
nome VARCHAR(30) NOT NULL UNIQUE,
descricao INT,
carga INT UNSIGNED,
totaulas INT UNSIGNED,
ano YEAR DEFAULT '2022'
) DEFAULT CHARSET = utf8;

ALTER TABLE cursos
ADD COLUMN idcurso INT FIRST;

ALTER TABLE cursos
ADD PRIMARY KEY (idcurso);

DROP TABLE cursos;