#SELECIONA QUANTOS CURSOS HÁ POR CARGA HORÁRIA
SELECT carga, COUNT(nome) FROM cursos
GROUP BY carga;

#MOSTRA CARGAS HORÁRIAS COM MAIS DE 5 CURSOS
SELECT carga, COUNT(nome) FROM cursos
GROUP BY carga
HAVING COUNT(nome) > 5;

#MOSTRA A CARGA E A QUANTIDADE DE CURSOS COM ESSA CARGA HORÁRIA
#QUE POSSUEM CARGA HORÁRIA MAIOR QUE A MÉDIA ENTRE TODOS OS CURSOS
SELECT carga, COUNT(nome) FROM cursos
WHERE ano > 2015
GROUP BY carga
HAVING carga > (SELECT AVG(carga) FROM CURSOS);